-->PART-A

--1
SELECT * FROM DEPOSIT

--2
SELECT * FROM BORROW

--3
SELECT * FROM CUSTOMERS

--4
SELECT ACTNO, CNAME, AMOUNT FROM DEPOSIT

--5
SELECT LOANNO, AMOUNT FROM BORROW

--6
SELECT * FROM BORROW
WHERE BNAME='ANDHERI'

--7
SELECT ACTNO, AMOUNT FROM DEPOSIT
WHERE ACTNO=106

--8
SELECT CNAME FROM BORROW
WHERE AMOUNT>5000

--9
SELECT CNAME FROM DEPOSIT
WHERE ADATE > '1995-12-01'

--10
SELECT ACTNO FROM DEPOSIT
WHERE ACTNO<105

--11
SELECT CNAME FROM CUSTOMERS
WHERE CITY='NAGPUR' OR CITY='DELHI'

SELECT CNAME FROM CUSTOMERS
WHERE CITY IN ('NAGPUR','DELHI')
 
 --12
SELECT CNAME FROM DEPOSIT
WHERE AMOUNT >4000 AND ACTNO>105

--13
SELECT * FROM BORROW
WHERE AMOUNT>3000 AND AMOUNT<8000

SELECT * FROM BORROW
WHERE AMOUNT BETWEEN 3000 AND 8000

--14
SELECT * FROM DEPOSIT
WHERE BNAME<>'ANDHERI'

--15
SELECT ACTNO, CNAME, AMOUNT FROM DEPOSIT
WHERE BNAME IN('AJNI', 'KAROLBAGH', 'M.G.ROAD') AND ACTNO<104


-->PART-B

--1
SELECT * FROM DEPOSIT

--2
SELECT TOP 5 * FROM DEPOSIT
WHERE AMOUNT>1000

--3
SELECT TOP 5 LOANNO, CNAME FROM BORROW
WHERE BNAME<>'ANDHERI'

--4
SELECT DISTINCT CITY FROM CUSTOMERS

--5
SELECT DISTINCT CITY FROM BRANCH

--> PART-C

--1 Retrieve top 50% record from table BORROW.
SELECT TOP 50 PERCENT * FROM BORROW

--2 Display top 10% amount from table DEPOSIT
SELECT TOP 10 PERCENT * FROM DEPOSIT

--3 Display top 25% customer who deposited more than 5000.
SELECT TOP 25 PERCENT * FROM DEPOSIT
WHERE AMOUNT>5000

--4 Retrieve first 10% Loan Amounts.
SELECT TOP 10 PERCENT AMOUNT FROM BORROW

--5 Retrieve all unique customer names with city.
SELECT DISTINCT CNAME , CITY FROM CUSTOMERS

--6 Retrieve all Loan records with one more column in Loan Amount as 10% extra amount.SELECT *, (AMOUNT*1.1) AS 'EXTRA AMOUNT' FROM BORROW--7 Retrieve all odd/even value loan number from Borrow table.SELECT * FROM BORROWWHERE LOANNO % 2=0